# Generated by Django 3.0.4 on 2020-06-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
